var positive_shape = 'oval'
var negative_shape = 'cross'
var neutral_shape_1 = 'diamond'
var neutral_shape_2 = 'pentagon'

var training_phase_trials = [
  { "shape": "cross", "word_type": "negative", "word": "ANXIOUS" },
  { "shape": "cross", "word_type": "negative", "word": "WOUNDS" },
  { "shape": "oval", "word_type": "positive", "word": "LUCKY" },
  { "shape": "diamond", "word_type": "negative", "word": "UNHAPPY" },
  { "shape": "pentagon", "word_type": "positive", "word": "CAREFREE" },
  { "shape": "oval", "word_type": "positive", "word": "BEAUTIFUL" },
  { "shape": "diamond", "word_type": "negative", "word": "DISCOURAGED" },
  { "shape": "pentagon", "word_type": "positive", "word": "LAUGHTER" },
  { "shape": "cross", "word_type": "positive", "word": "MIRACLE" },
  { "shape": "pentagon", "word_type": "negative", "word": "GRIEF" },
  { "shape": "pentagon", "word_type": "negative", "word": "AMBULANCE" },
  { "shape": "oval", "word_type": "positive", "word": "FAMILY" },
  { "shape": "cross", "word_type": "negative", "word": "DEPRESSED" },
  { "shape": "oval", "word_type": "negative", "word": "DEATH" },
  { "shape": "diamond", "word_type": "positive", "word": "REWARD" },
  { "shape": "oval", "word_type": "negative", "word": "CHAOS" },
  { "shape": "diamond", "word_type": "negative", "word": "GERMS" },
  { "shape": "cross", "word_type": "negative", "word": "PRESSURE" },
  { "shape": "pentagon", "word_type": "negative", "word": "MUCUS" },
  { "shape": "oval", "word_type": "positive", "word": "VICTORY" },
  { "shape": "cross", "word_type": "negative", "word": "WASTE" },
  { "shape": "cross", "word_type": "negative", "word": "ANGRY" },
  { "shape": "diamond", "word_type": "negative", "word": "PANIC" },
  { "shape": "oval", "word_type": "negative", "word": "ANGUISHED" },
  { "shape": "cross", "word_type": "negative", "word": "TRAUMA" },
  { "shape": "pentagon", "word_type": "negative", "word": "TRAGEDY" },
  { "shape": "oval", "word_type": "positive", "word": "JOY" },
  { "shape": "cross", "word_type": "negative", "word": "STRESS" },
  { "shape": "pentagon", "word_type": "negative", "word": "ROUGH" },
  { "shape": "oval", "word_type": "positive", "word": "HOPEFUL" },
  { "shape": "pentagon", "word_type": "positive", "word": "SAFE" },
  { "shape": "cross", "word_type": "negative", "word": "NIGHTMARE" },
  { "shape": "oval", "word_type": "positive", "word": "PROGRESS" },
  { "shape": "pentagon", "word_type": "negative", "word": "OUTRAGE" },
  { "shape": "pentagon", "word_type": "positive", "word": "ACCEPTANCE" },
  { "shape": "pentagon", "word_type": "positive", "word": "TERRIFIC" },
  { "shape": "diamond", "word_type": "negative", "word": "VICTIM" },
  { "shape": "diamond", "word_type": "positive", "word": "GRATEFUL" },
  { "shape": "cross", "word_type": "negative", "word": "LONELINESS" },
  { "shape": "oval", "word_type": "positive", "word": "DREAM" },
  { "shape": "diamond", "word_type": "negative", "word": "DESPAIRING" },
  { "shape": "diamond", "word_type": "positive", "word": "KINDNESS" },
  { "shape": "pentagon", "word_type": "negative", "word": "SCARED" },
  { "shape": "diamond", "word_type": "positive", "word": "PROTECTED" },
  { "shape": "cross", "word_type": "negative", "word": "HELPLESS" },
  { "shape": "pentagon", "word_type": "negative", "word": "SEVERE" },
  { "shape": "oval", "word_type": "positive", "word": "FLOWER" },
  { "shape": "cross", "word_type": "positive", "word": "CONFIDENT" },
  { "shape": "diamond", "word_type": "positive", "word": "OPTIMISM" },
  { "shape": "diamond", "word_type": "positive", "word": "EASYGOING" },
  { "shape": "oval", "word_type": "negative", "word": "HOSPITAL" },
  { "shape": "cross", "word_type": "negative", "word": "BROKEN" },
  { "shape": "oval", "word_type": "positive", "word": "ACHIEVEMENT" },
  { "shape": "diamond", "word_type": "negative", "word": "USELESS" },
  { "shape": "cross", "word_type": "positive", "word": "RESCUE" },
  { "shape": "oval", "word_type": "positive", "word": "CHEER" },
  { "shape": "oval", "word_type": "positive", "word": "LIVELY" },
  { "shape": "pentagon", "word_type": "positive", "word": "GOOD" },
  { "shape": "cross", "word_type": "negative", "word": "OVERWHELMED" },
  { "shape": "oval", "word_type": "positive", "word": "THOUGHTFUL" },
  { "shape": "oval", "word_type": "positive", "word": "SOOTHE" },
  { "shape": "cross", "word_type": "positive", "word": "TRIUMPHANT" },
  { "shape": "pentagon", "word_type": "negative", "word": "INFECTION" },
  { "shape": "diamond", "word_type": "positive", "word": "HUG" },
  { "shape": "pentagon", "word_type": "positive", "word": "LEISURELY" },
  { "shape": "diamond", "word_type": "positive", "word": "SOCIAL" },
  { "shape": "oval", "word_type": "positive", "word": "FREEDOM" },
  { "shape": "oval", "word_type": "positive", "word": "FUN" },
  { "shape": "diamond", "word_type": "negative", "word": "FEVER" },
  { "shape": "pentagon", "word_type": "positive", "word": "BRAVE" },
  { "shape": "cross", "word_type": "negative", "word": "INSECURE" },
  { "shape": "diamond", "word_type": "positive", "word": "RAINBOW" },
  { "shape": "cross", "word_type": "negative", "word": "SICK" },
  { "shape": "pentagon", "word_type": "positive", "word": "RELAXED" },
  { "shape": "cross", "word_type": "negative", "word": "DISTRESSED" },
  { "shape": "pentagon", "word_type": "negative", "word": "SUFFOCATE" },
  { "shape": "diamond", "word_type": "negative", "word": "FATIGUED" },
  { "shape": "diamond", "word_type": "positive", "word": "IMPROVE" },
  { "shape": "pentagon", "word_type": "positive", "word": "COMFORT" },
  { "shape": "diamond", "word_type": "negative", "word": "BURIAL" }
]

